#!/bin/sh

prepare_dirs() {
  LOGDIR=/var/log/wallarm
  TARANTOOL_LOGFILE=$LOGDIR/tarantool.log

  chown wallarm:wallarm $LOGDIR
  chmod 0750 $LOGDIR

  touch $TARANTOOL_LOGFILE
  chown wallarm:wallarm $TARANTOOL_LOGFILE

  touch /etc/crontab /etc/cron.d/*

  mkdir -p /run/supervisor
}

register_node() {
  args="--batch --no-sync"

  WALLARM_API_USE_SSL="${WALLARM_API_USE_SSL:-true}"
  WALLARM_API_CA_VERIFY="${WALLARM_API_CA_VERIFY:-true}"

  if [ -n "${DEPLOY_FORCE}" ]; then
    args="$args --force"
  fi

  if [ -n "$WALLARM_API_HOST" ]; then
    args="$args -H $WALLARM_API_HOST"
  fi

  if [ -n "$WALLARM_API_PORT" ]; then
    args="$args -P $WALLARM_API_PORT"
  fi

  if [ x"$WALLARM_API_USE_SSL" = x"false" ] \
     || [ x"$WALLARM_API_USE_SSL" = x"False" ] \
     || [ x"$WALLARM_API_USE_SSL" = x"no" ]
  then
    args="$args --no-ssl"
  fi

  if [ x"$WALLARM_API_CA_VERIFY" = x"false" ] \
     || [ x"$WALLARM_API_CA_VERIFY" = x"False" ] \
     || [ x"$WALLARM_API_CA_VERIFY" = x"no" ]
  then
    args="$args --no-verify"
  fi

  if [ -e /etc/wallarm/node.yaml ] \
     && [ -s /etc/wallarm/node.yaml ]
  then
    echo "Node registartion skipped - node.yaml already exists"
  elif [ -n "$NODE_UUID" ] \
       && [ -n "$NODE_SECRET" ]
  then
    /usr/share/wallarm-common/addnode \
      $args \
      --uuid "$NODE_UUID" \
      --secret "$NODE_SECRET"
  else
    /usr/share/wallarm-common/addnode \
      $args \
      --username "$DEPLOY_USER" \
      --password "$DEPLOY_PASSWORD"
  fi
}

sync_node() {
  cmd="/usr/share/wallarm-common/syncnode -l STDOUT"

  for i in $(seq 1 3); do
    if $cmd; then
      break
    elif [ -f /etc/wallarm/proton.db ] && [ -f /etc/wallarm/lom ]; then
      break
    else
      echo "Wait before next syncnode attempt..."
      sleep 5
    fi
  done
}

configure_nginx() {
  [ -n "$NGINX_BACKEND" ] || return 0

  if [ "$NGINX_BACKEND" = "${NGINX_BACKEND#http://}" ] \
     && [ "$NGINX_BACKEND" = "${NGINX_BACKEND#https://}" ]
  then
    sed -i -e "s#proxy_pass .*#proxy_pass http://$NGINX_BACKEND;#" \
      /etc/nginx/sites-enabled/default
  else
    sed -i -e "s#proxy_pass .*#proxy_pass $NGINX_BACKEND;#" \
      /etc/nginx/sites-enabled/default
  fi

  sed -i -e "s@# wallarm_mode .*@wallarm_mode ${WALLARM_MODE:-monitoring};@" \
    /etc/nginx/sites-enabled/default

  if [ -n "$WALLARM_STATUS_ALLOW" ]; then
    craft_wallarm_status_snippet
    insert_wallarm_status_snippet
  fi

  if [ x"${WALLARM_NGINX_LOG_TO_FILES}" != x"true" ]
  then
    ln -sf /dev/stdout /var/log/nginx/access.log
    ln -sf /dev/stderr /var/log/nginx/error.log
  fi
}

craft_wallarm_status_snippet() {
  {
    printf "\tlocation /wallarm-status {\n"
    for cidr in $(echo "$WALLARM_STATUS_ALLOW" | sed "s/,/ /g"); do
      printf "\t\tallow %s;\n" "$cidr"
    done
    printf "\t\tdeny all;\n"
    printf "\t\twallarm_status on;\n"
    printf "\t\twallarm_mode off;\n"
    printf "\t}\n\n"
  } >/tmp/wallarm-status.conf
}

insert_wallarm_status_snippet() {
  line_for_insert=$(grep -n "location / {" /etc/nginx/sites-enabled/default | cut -f 1 -d:)
  line_for_insert=$((line_for_insert - 1))
  sed -i "${line_for_insert}r /tmp/wallarm-status.conf" /etc/nginx/sites-enabled/default
}

if [ "${1}" = "--source-only" ]
then
  return
fi

if [ x"$WALLARM_FALLBACK" = x"false" ]
then
  set -e
fi

if [ "x${SLAB_ALLOC_ARENA}" = 'x' ]; then
  if [ -n "$TARANTOOL_MEMORY_GB" ]; then
    SLAB_ALLOC_ARENA=$TARANTOOL_MEMORY_GB
    export SLAB_ALLOC_ARENA
  fi
fi


if [ -z "$DEPLOY_USER" ] || [ -z "$DEPLOY_PASSWORD" ]; then
  if [ ! -f "/etc/wallarm/license.key" ]; then
    echo "ERROR: no DEPLOY_USER or DEPLOY_PASSWORD and no license key in /etc/wallarm/license.key" >&2
    exit 1
  fi
fi


prepare_dirs
register_node
sync_node
configure_nginx

exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
