#!/bin/sh

set -e

if [ -z "$PROTONDB_UPDATED" ] \
   && [ -z "$LOM_UPDATED" ]; then
	exit 42
fi

if [ ! -f  /run/nginx.pid ]; then
  exit 42
fi

pid="$(cat /run/nginx.pid)"

if [ -z "$pid" ]; then
  exit 42
fi

kill -HUP "$pid"
